# Generated by Django 3.0.3 on 2021-05-16 00:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_rememberaccount_accept_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(default=None, max_length=300, null=True)),
                ('category', models.CharField(default='Default', max_length=50)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.RememberAccount')),
            ],
        ),
    ]
