# Generated by Django 3.0.3 on 2021-01-01 22:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('type', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.RememberAccount')),
            ],
            options={
                'permissions': (('send_invite', 'Send Invite'),),
            },
        ),
        migrations.CreateModel(
            name='MemoryLineParticipants',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('memory_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memory_line.MemoryLine')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.RememberAccount')),
            ],
        ),
        migrations.AddField(
            model_name='memoryline',
            name='participants',
            field=models.ManyToManyField(related_name='participants', through='memory_line.MemoryLineParticipants', to='accounts.RememberAccount'),
        ),
        migrations.AddField(
            model_name='memoryline',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type.Type'),
        ),
    ]
