# Generated by Django 3.0.3 on 2021-01-01 22:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TypeOwner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.RememberAccount')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='type.Type')),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='owners',
            field=models.ManyToManyField(related_name='owners', through='type.TypeOwner', to='accounts.RememberAccount'),
        ),
    ]
